name: GitHub Actions Demo
on: 
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '0 22 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'auto run'
        run: python SunnyRunning.py
        with:
          IMEI: ${{ secrets.IEMI }}
          mail_host: ${{ secrets.mail_host }}
          mail_user: ${{ secrets.mail_user }}
          mail_pass: ${{ secrets.mail_pass }}
          mail_sender: ${{ secrets.mail_sender }}
          mail_recever: ${{ secrets.mail_recever }}
          mail_from: ${{ secrets.mail_to }}